# Generated by Django 5.0 on 2024-09-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contact_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
