# Generated by Django 5.0 on 2024-09-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_contact_form_error_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_form',
            new_name='contact_form_info',
        ),
    ]
